<div id="topBanner">
	<a id="pnnlLogo" href="https://www.pnl.gov/">
    <img src="/images/pnnl_logo.png" alt="Pacific Northwest National Laboratory." style="width:200px; height:auto;">
	</a>
	<a id="doeLink" href="http://energy.gov/">
    <img src="/images/doe_logo.png" alt="U.S. Department of Energy" style="width:200px; height:auto;">
	</a>
</div>
<div id="subBanner">
    <img src="/images/smbanner.jpg" width="956" height="51"
        alt="PNNL: Global Arrays Toolkit" />
</div>

